name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PYTHONPATH=$PYTHONPATH:/workspace

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:/workspace
        pytest --maxfail=1 --disable-warnings -q
